version: "3"

services:
  postgres:
    image: postgres:13
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - terra-classic
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
  # redis:
  #   image: redis:latest
  #   networks:
  #     - terra
  #   ports:
  #     - "6379:6379"
networks:
  terra:
    driver: bridge